- CMakeLists.txt
- src/CMakeLists.txt
- src/common/filters/Filter.h
- src/common/filters/RegexFilter.h
- src/services/common/ToolWrapper.h
- src/services/nvvp/CMakeLists.txt
- src/services/nvvp/nvvp.cpp
> Improve NVVP service with regular expressions

- src/services/common/ToolWrapper.h
- src/services/nvvp/nvvp.cpp
- src/services/vtune/vtune.cpp
Hey, removed the pure CRTP stuff, replaced with virtual inheritance. Don't merge yet, just wanted to push so you could see what it looks like. Actually, those functions shouldn't be pure virtual, they should be defaulted. Nonetheless, this is one of Tom's (@trws) bits of magic
> NVVP service refactoring

- src/caliper/CaliFunctional.h
Huge changes, very impressive. Should make the instrumenter plugin work
> Tiny fix to code

- .travis.yml
- README.md
- codecov.yml
Should be everything you need for the basics of code coverage.
> Added code coverage

- src/services/libpfm/Libpfm.cpp
NOW counters are resetting correctly :)
> Reset counters after reading

- example_conf/counter_summary.conf
- src/services/libpfm/Libpfm.cpp
This was messing with topdown metrics.
> Remove scaling, which is done incorrectly

- src/caliper/AllocTracker.cpp
- test/ci_app_tests/CMakeLists.txt
- test/ci_app_tests/ci_test_alloc_hooks.c
- test/ci_app_tests/test_allocservice.py
Also includes fix for accessing the last element
> Test alloc hooks

- src/reader/JsonFormatter.cpp
> First row is global across cali-query processes

- doc/sphinx/index.rst
> Update Caliper intro md.rst

- include/caliper/Caliper.h
- include/caliper/SnapshotRecord.h
- src/caliper/Caliper.cpp
- src/caliper/SnapshotRecord.cpp
- src/caliper/test/test_attribute.cpp
- src/caliper/test/test_channel_api.cpp
- src/common/OutputStream.cpp
- src/services/instlookup/InstLookup.cpp
- src/services/symbollookup/SymbolLookup.cpp
- src/services/validator/validator.cpp
- test/cali-test.cpp
- test/ci_app_tests/ci_test_basic.cpp
- test/ci_app_tests/test_basictrace.py
Also fixes config sanity check variable snafu.
> More cleanup and more tests

- include/caliper/Annotation.h
- include/caliper/common/Variant.h
- include/caliper/common/cali_variant.h
- src/common/cali_variant.c
- src/common/test/test_c_variant.cpp
- src/common/test/test_variant.cpp
- test/ci_app_tests/ci_test_basic.cpp
Also added in C code for making a variant from a C string.
> Added in Variant constructors from a size_t and a const char*. 

- include/caliper/ConfigManager.h
- src/caliper/ConfigManager.cpp
- src/caliper/controllers/EventTraceController.cpp
- src/caliper/controllers/NvProfController.cpp
- src/caliper/controllers/RuntimeReportController.cpp
- src/caliper/test/test_configmanager.cpp
- src/mpi-rt/controllers/SpotController.cpp
- src/mpi-rt/controllers/SpotV1Controller.cpp
- src/tools/cali-query/cali-query.cpp
Adds ability to check for and report errors in controller config arguments.
> Implement parameter error checking for controllers

- src/services/kokkos/KokkosProfilingSymbols.cpp
Nothing to see here, nope no braindead mistakes in my code nosiree
> Nothing to see here

- doc/sphinx/calql.rst
- include/caliper/reader/Aggregator.h
- include/caliper/reader/Preprocessor.h
- include/caliper/reader/QuerySpec.h
- src/mpi/services/mpireport/MpiReport.cpp
- src/reader/CMakeLists.txt
- src/reader/CalQLParser.cpp
- src/reader/Preprocessor.cpp
- src/reader/QueryProcessor.cpp
- src/reader/test/CMakeLists.txt
- src/reader/test/test_calqlparser.cpp
- src/reader/test/test_preprocessor.cpp
- src/tools/cali-query/cali-query.cpp
- src/tools/mpi-caliquery/mpi-caliquery.cpp
Adds a new query system mechanism to apply computations on input records before processing
> Add CalQL LET clause

- src/mpi/controllers/LoopReportController.cpp
- src/services/monitor/LoopMonitor.cpp
- test/ci_app_tests/test_loopreport.py
- test/ci_app_tests/test_monitor.py
Lets users select target loops for loop-report.
> Add loop selection in loop_monitor and loop-report

- src/services/kokkos/KokkosProfilingSymbols.cpp
- src/services/kokkos/KokkosTime.cpp
- src/services/kokkos/types.hpp
We're adding in fence support for Kokkos Profiling in kokkos/kokkos#2891 . Once that merges, this will add fence profiling to Caliper.
> Kokkos Fencing

- src/caliper/CMakeLists.txt
- src/caliper/Caliper.cpp
- src/caliper/builtin_configmanager.cpp
- test/ci_app_tests/test_basictrace.py
- test/ci_app_tests/test_log.py
Use CALI_CONFIG to enable ConfigManager configurations with an environment variable.
> Add built-in ConfigManager

- src/services/callpath/Callpath.cpp
This is a fix for building on aarch64.
Could you please marge my fix to Caliper?
> support for aarch64

- doc/sphinx/calql.rst
- include/caliper/reader/QuerySpec.h
- include/caliper/reader/RecordSelector.h
- src/reader/CalQLParser.cpp
- src/reader/Preprocessor.cpp
- src/reader/RecordSelector.cpp
- src/reader/test/test_calqlparser.cpp
- src/reader/test/test_preprocessor.cpp
A nice new query functionality
> calql: Add LET ... IF

- CMakeLists.txt
We had one place left where we said "WITH_KOKKOS_PROFILING"
> Fixed Kokkos build

- include/caliper/ChannelController.h
- include/caliper/CollectiveOutputChannel.h
- include/caliper/ConfigManager.h
- include/caliper/cali-mpi.h
- src/caliper/ChannelController.cpp
- src/caliper/ConfigManager.cpp
- src/mpi/CMakeLists.txt
- src/mpi/CollectiveOutputChannel.cpp
- src/mpi/collective_flush.cpp
- src/mpi/services/mpireport/MpiReport.cpp
- test/ci_app_tests/CMakeLists.txt
- test/ci_app_tests/ci_test_collective_output_channel.cpp
- test/ci_app_tests/test_mpi.py
Adds CollectiveOutputChannel class for streaming aggregate reports to a C++ std::ostream.
> Add mechanisms for streaming to std::ostream

- doc/sphinx/CUDA.rst
- doc/sphinx/CaliperBasics.rst
- doc/sphinx/OpenMP.rst
- doc/sphinx/OutputFormats.rst
- doc/sphinx/configuration.rst
- doc/sphinx/index.rst
- doc/sphinx/services.rst
- examples/apps/CMakeLists.txt
- examples/apps/collective-output-channel.cpp
- include/caliper/CollectiveOutputChannel.h
- src/caliper/controllers/controllers.cpp
Adds howto guides for OpenMP and CUDA profiling, plus many minor updates.
> Documentation update

- doc/sphinx/conf.py.in
- doc/sphinx/index.rst
- doc/sphinx/pythonreader.rst
- python/caliper-reader/LICENSE
- python/caliper-reader/caliperreader/caliperreader.py
- python/caliper-reader/caliperreader/caliperstreamreader.py
- python/caliper-reader/caliperreader/metadatadb.py
- python/caliper-reader/caliperreader/version.py
- python/caliper-reader/tests/test_reader.py
Adds `Attribute.metadata()` and `Attribute.is_global()`, as well as documentation updates.
> Update python reader

- python/caliper-reader/caliperreader/caliperreader.py
- python/caliper-reader/caliperreader/caliperstreamreader.py
- python/caliper-reader/caliperreader/metadatadb.py
- python/caliper-reader/caliperreader/version.py
- python/caliper-reader/tests/test_reader.py
Also adds access to more attribute metadata.
> python reader: Skip hidden attributes

- ext/gotcha/src/gotcha_dl.c
Temporary workaround to fix build with glibc 2.34+. Probably breaks calling a wrapped dlsym() with RTLD_NEXT, but that should be a rare case.
> Add temporary gotcha build workaround for glibc 2.34+

- src/caliper/controllers/ROCmActivityProfileController.cpp
- src/caliper/controllers/ROCmActivityReportController.cpp
- src/caliper/controllers/controllers.cpp
- src/services/roctracer/RocTracer.cpp
Roctracer flushes are now processed immediately when the tracer buffer is full.
> Reengineer roctracer flushes

- src/services/callpath/Callpath.cpp
- src/services/sampler/Sampler.cpp
Initialize libunwind cursor in sample handler and jump out of the sample handler context. This removes the `__restore_rt` entries from Caliper stack traces and should make sampling configs much more useful.
> Fix call stack unwinding

- src/caliper/controllers/HatchetSampleProfileController.cpp
- src/caliper/controllers/SampleReportController.cpp
- src/caliper/controllers/controllers.cpp
- test/ci_app_tests/test_symbollookup.py
> Update sampling controllers

- include/caliper/Caliper.h
- src/caliper/Caliper.cpp
- src/caliper/cali.cpp
A few more performance optimizations
> Add separate end_with_value_check() call

- src/services/variorum/Variorum.cpp
```
Run completed:
Problem size        =  30
MPI tasks           =  1
Iteration count     =  932
Final Origin Energy =  2.025075e+05
Testing Plane 0 of Energy Array on rank 0:
MaxAbsDiff   = 6.912160e-11
TotalAbsDiff = 8.366235e-10
MaxRelDiff   = 1.427988e-12
Elapsed time         =    2.1e+02 (s)
Grind time (us/z/c)  =  8.4413169 (per dom)  (  212.4173 overall)
FOM                  =  118.46493 (z/s)
== CALIPER: (0): Finalizing ... 
== CALIPER: (0): default: Flushing Caliper data
== CALIPER: (0): default: Aggregate: flushed 146 snapshots.
event.begin#region              min#variorum.val.power_node_watts max#variorum.val.power_node_watts sum#variorum.val.power_node_watts avg#variorum.val.power_node_watts min#variorum.power_node_watts max#variorum.power_node_watts …
```
> update variorum service to char string

- .github/workflows/cmake.yml
- examples/configs/flops.json
- python/cali2traceevent.py
- src/caliper/RegionProfile.cpp
- src/caliper/controllers/HatchetRegionProfileController.cpp
- src/caliper/controllers/LoopReportController.cpp
- src/caliper/controllers/OpenMPReportController.cpp
- src/caliper/controllers/ROCmActivityProfileController.cpp
- src/caliper/controllers/ROCmActivityReportController.cpp
- src/caliper/controllers/RuntimeReportController.cpp
- src/caliper/controllers/SpotController.cpp
- src/caliper/controllers/controllers.cpp
- src/services/timer/Timer.cpp
- test/ci_app_tests/test_aggregate.py
- test/ci_app_tests/test_basictrace.py
- test/ci_app_tests/test_c_api.py
- test/ci_app_tests/test_caliquery.py
- test/ci_app_tests/test_fortran_api.py
- test/ci_app_tests/test_json.py
- test/ci_app_tests/test_spot.py
> Increase timer resolution

- include/caliper/ConfigManager.h
- src/caliper/ConfigManager.cpp
- src/caliper/controllers/controllers.cpp
Reports visits and min/max/avg time per visit.
> Add region.stats metric option

- src/caliper/Caliper.cpp
Seems to give ~10% performance improvement for taking snapshots.
> Use persistent snapshot buffer

- src/caliper/MemoryPool.cpp
- src/caliper/MetadataTree.cpp
Also reduces initial memory pool size.
> Fix memory pool size reporting

- ext/gotcha/include/gotcha/gotcha.h
- ext/gotcha/include/gotcha/gotcha_types.h
- ext/gotcha/src/elf_ops.c
- ext/gotcha/src/elf_ops.h
- ext/gotcha/src/gotcha.c
- ext/gotcha/src/gotcha_auxv.c
- ext/gotcha/src/gotcha_auxv.h
- ext/gotcha/src/gotcha_dl.c
- ext/gotcha/src/gotcha_dl.h
- ext/gotcha/src/gotcha_utils.c
- ext/gotcha/src/gotcha_utils.h
- ext/gotcha/src/hash.c
- ext/gotcha/src/hash.h
- ext/gotcha/src/libc_wrappers.c
- ext/gotcha/src/libc_wrappers.h
- ext/gotcha/src/library_filters.c
- ext/gotcha/src/library_filters.h
- ext/gotcha/src/tool.c
- ext/gotcha/src/tool.h
- ext/gotcha/src/translations.c
- ext/gotcha/src/translations.h
Use latest gotcha develop which hopefully addresses #529
> Update gotcha. Should fix #529

- include/caliper/common/OutputStream.h
- include/caliper/reader/FormatProcessor.h
- src/caliper/controllers/CudaActivityReportController.cpp
- src/caliper/controllers/ROCmActivityReportController.cpp
- src/caliper/controllers/RuntimeReportController.cpp
- src/caliper/controllers/SampleReportController.cpp
- src/common/OutputStream.cpp
- src/services/mpireport/MpiReport.cpp
- src/services/report/Report.cpp
Add option to append to file for report configs. Fixes #536
> Add option to append to file

- include/caliper/ConfigManager.h
- src/caliper/ConfigManager.cpp
- src/reader/FormatProcessor.cpp
- src/services/Services.cpp
- src/services/Services.h
- src/tools/cali-query/query_common.cpp
- test/ci_app_tests/test_caliquery.py
Adds help for CalQL and CalQL statements. Also improves --help configs and --help services output.
> Improve cali-query --help

- src/caliper/controllers/HatchetRegionProfileController.cpp
- src/caliper/controllers/HatchetSampleProfileController.cpp
- src/caliper/controllers/SpotController.cpp
- src/caliper/controllers/controllers.cpp
- src/services/CMakeLists.txt
- src/services/LCNodeInfoService.cpp
- test/ci_app_tests/CMakeLists.txt
- test/ci_app_tests/example_node_info.json
- test/ci_app_tests/test_basictrace.py
Reads node info from `/etc/node_info.json` on LC systems
> Add lcnodeinfo service

- src/caliper/Caliper.cpp
- src/caliper/ChannelController.cpp
- src/caliper/cali.cpp
Channels now must be activated explicitly
> Rewire active channel logic

- examples/apps/CMakeLists.txt
- examples/apps/async_event.cpp
- include/caliper/AsyncEvent.h
- include/caliper/Caliper.h
- src/caliper/AsyncEvent.cpp
- src/caliper/CMakeLists.txt
- src/caliper/Caliper.cpp
- src/caliper/controllers/controllers.cpp
- src/services/event/AsyncEventTrigger.cpp
- src/services/event/CMakeLists.txt
- src/services/mpiwrap/MpiPattern.cpp
- src/services/mpiwrap/MpiPattern.h
- src/services/mpiwrap/Wrapper.w
Adds `TimedAsyncEvent` which can track an event across regions and threads. Also adds MPI Irecv gap time stats for MPI pattern analysis.
> Add async events

- src/caliper/controllers/ROCmActivityProfileController.cpp
- src/services/rocprofiler/RocProfiler.cpp
Adds min/max/avg activity duration and MPI rank in rocm-activity-report.
> More stats and MPI rank for rocm profiles

- .gitlab-ci.yml
- .uberenv_config.json
- scripts/gitlab/build-and-test.sh
Reverts LLNL/Caliper#645
@daboehme #645 is a work in progress. It was passing the tests, but the process always involves working on moving references in Spack and radiuss-spack-configs and requires merge there before merging in our projects.
Sorry for the confusion.
> Revert "[WIP] Update packages"

- include/caliper/common/Entry.h
- src/tools/cali-query/cali-query.cpp
Remove threading from cali-query which was very rarely used.
> Simplify cali-query

- .gitlab-ci.yml
- .uberenv_config.json
- scripts/gitlab/build-and-test.sh
This PR needs changes to be merged in spack and radiuss-spack-configs first.
> [WIP] Update packages

- src/reader/Aggregator.cpp
Simplifies a lot of boilerplate code for the CalQL aggregator kernels
> Streamline aggregator implementation

- src/reader/Aggregator.cpp
Removes the per-kernel locks - we're not running this in parallel anymore anyway.
> More aggregator streamlining

- src/services/nvtx/Nvtx.cpp
Fixes #668. Thanks @pauleonix for reporting.
> Switch to nvtx3 header

- src/services/io/CurIOus/src/file_registry.c
> Fix potential segfault in io service
