LLNL/Caliper

- caliper-config.h.in
Hey, the service wasn't mentioned in caliper-config.h.in, which didn't yet cause problems, but might cause them in the future
> HOTFIX: One-liner adding CALIPER_HAVE_TAU to the config line

- src/common/filters/RegexFilter.h
Rather than compiling a regex every time, this allows us to just compile (and optimize) the regex once. Begins to resolve comments from @trws on #7
> Optimized the regex filtering

- src/reader/CMakeLists.txt
- src/reader/Json.cpp
- src/reader/Json.h
- src/tools/cali-query/cali-query.cpp
This PR is absolutely not just changing the formatting in Table.h. Come to think of it, we should make that a base class with "processHeader" and "processRow" functions.  I'll leave that to wiser (and more patient) minds, this should allow Caliper to interface with the web tools we're developing around the lab
> Added flag to cali-query to emit JSON compatible output

- cmake/FindLibcurl.cmake
Most linux distros put curl.h in a subdir curl, e.g.
http://packages.ubuntu.com/search?searchon=contents&keywords=curl.h&mode=exactfilename&suite=yakkety&arch=any
> FindLibcurl.cmake: add path suffix

- src/services/CMakeLists.txt
Tiny fix:
Right now we assume in exactly one place that the root of Caliper is CMAKE_SRC_DIR. This is not necessarily true, there are build systems which include third party libraries as git submodules that become CMake subdirectories in the eventual build. Caliper broke in one such code's build due to the deleted line I [highlight](https://github.com/LLNL/Caliper/pull/38/files#diff-ed082c60e62182b0788deea7c7ca1195L5). Let me know if this fix doesn't work or you want a different solution, I'm a little ignorant of the design decisions in that part of CMake.
> Allow Caliper to be included as a subdirectory in a CMake build

- src/reader/JsonFormatter.cpp
… after the first record has been parsed
Fix for #67 
This also adds a newline after the start of the list, which should be fine.
> Fix for #67

- src/services/sos/Sos.cpp
The SOS service is calling SOS_publish(...) and transmitting data to the daemon (apparently) as independent actions for each element of each snapshot. The desired behaviour is for calls to SOS_pack_related(...) to enqueue these values in the (SOS_pub*) sos_pub handle, and only once at the triggering event connect and transmit all enqueued values.
> Correct SOS service pack/publish behavior

- include/caliper/common/cali_variant.h
* Avoid using ANSI C union initialization that isn't also 	legal C++.  This change should work for both languages without loss of performance.
> Modify cali_variant.h to make it legal C++

- include/caliper/CaliFunctional.h
- test/cali-functional-debugging.cpp
Putting this up so you (@daboehme ) can have the code which triggers this behavior.
For people who aren't David B, this is something I've used to debug code, you can define types as "Recordable" and make "Recordable" functions, any time a Recordable object to a Recordable function, it gets recorded.
I've been using it to validate certain stuff in apps, but it's mainly for you to have a reproducer for the formatting issues I was seeing.
> Debugging Utility in CaliFunctional

- include/caliper/Annotation.h
- include/caliper/Caliper.h
- src/caliper/Annotation.cpp
- src/caliper/Caliper.cpp
@daboehme , I'm a little unsure what's expensive in Caliper, I think my implementation is a good one, but want some backup to make sure I'm not screwing anything up.
On Annotation creation, we look up Annotations of the same name. If the Annotation doesn't already exist, we fill up the metadata items with what they need (keys and values).
On a begin or a set, we try to establish the metadata. First we check if any metadata keys exist, and if not we short circuit out. If keys exist, we create the attribute. Once done, we wipe out the metadata keys, which will lead future calls to establish_metadata to short circuit out.
> C++ Metadata Interface

- src/caliper/cali.cpp
- src/services/spot/Spot.cpp
Sorry about this one. Turns out that we had two bugs
1) BG/Q Clang not supporting std::vector<T>::emplace
2) PGI having trouble with rapidjson, our JSON handling library
Solving (1) was template metaprogramming: check if vector emplace exists (check that its return type equals its return type). If it does, use emplace, otherwise use insert. If you want to just use insert everywhere, feel free, I just wanted to use it everywhere we can.
Solving (2) was bad preprocessor hacking. If we're using PGI, before including PGI, I mess with our preprocessor definitions, then restore them after [(thanks to these folks for the idea.)](https://github.com/Tencent/rapidjson/issues/1115)
None of this is pretty, but it makes us more portable.
> Fix for the BG/Q Clang compilers. Also, PGI's handling of Rapidjson

- include/caliper/common/util/spinlock.hpp
- src/caliper/Blackboard.h
Per the standard, std::atomic_flag constructor doesn't have to be constexpr, though the Apple compiler was the only one having a problem with this.
> Remove constexpr spinlock constructor. Fixes #160

- include/caliper/Annotation.h
- test/ci_app_tests/ci_test_basic.cpp
This will allow us to do whatever we want in Variant, and have Annotation be able to play nicely with it. Good call by @mrzv that in the single-arg case we can do this without variadics, getting most of the benefit without C++11
The "std::enable_if" prevents infinite recursion, which I think would happen otherwise.
If this is good, we can put together another PR with changes to Variant including std::size_t and such
> "Forwarding" Annotation calls to Variant

- include/caliper/ConfigManager.h
- src/caliper/ConfigManager.cpp
- src/caliper/controllers/controllers.cpp
- src/mpi-rt/setup_mpi.cpp
- src/tools/cali-query/cali-query.cpp
Caliper had an initialization order bug with the intel compiler.  The ConfigInfo objects were being copied into ConfigInfoLists at initialization time.  But the intel compiler wasn't treating them as POD, which meant they were being initialized by a constructor.  If the copy ConfigInfo to ConfigInfoList constructor ran before the ConfigInfo constructor, then incomplete objects would get copied.
This makes the ConfigInfoList track ConfigInfo by pointer, rather than by copy.
> Fix initialization order bug 

- src/services/io/CurIOus/src/file_registry.c
```console
../external/caliper/src/services/io/CurIOus/src/file_registry.c: In function 'curious_register_file_by_fd':
../external/caliper/src/services/io/CurIOus/src/file_registry.c:54:36: warning: '%d' directive output may be truncated writing between 1 and 10 bytes into a region of size 6 [-Wformat-truncation=]
snprintf(fd_path + len, DIGITS, "%d", fd);
^~
../external/caliper/src/services/io/CurIOus/src/file_registry.c:54:35: note: directive argument in the range [0, 2147483647]
snprintf(fd_path + len, DIGITS, "%d", fd);
^~~~
In file included from /usr/include/stdio.h:862,
from ../external/caliper/src/services/io/CurIOus/src/file_registry.c:4:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: '__builtin___snprintf_chk' output between 2 and 11 bytes into a destination of size 6 …
```
> Fixed -Wformat-trunction warning with GCC by checking return value 

- src/services/timestamp/Timestamp.cpp
As you may know (at least I was told you know) we are integrating Caliper into our monitoring framework [DCDB](http://dcdb.it). For this we would like the timestamp service to provide absolute timestamps with sub-second precision.
Ideally, the timestamps use nanosecond precision like in this PR, but anything more fine grained than seconds would do the trick.
Another option would be to make the precision configurable like for the snapshot duration.
Let me know what you think
> Timestamp service: Change precision of timestamps to nanoseconds

- ext/gotcha/src/libc_wrappers.c
Pull in change from upstream gotcha to fix #249. Thanks @mastino for reporting.
> Update built-in gotcha's open() wrapper. Fixes #249

- include/caliper/common/cali_types.h
- src/caliper/Caliper.cpp
- src/caliper/cali.cpp
- src/caliper/test/test_channel_api.cpp
- src/common/cali_types.c
- src/services/pthread/PthreadService.cpp
- src/tools/cali-query/cali-query.cpp
- test/ci_app_tests/ci_test_binding.cpp
- test/ci_app_tests/ci_test_c_ann.c
- test/ci_app_tests/ci_test_thread.cpp
- test/ci_app_tests/test_pthread.py
Caliper supports overlapping annotation regions (i.e., ```begin(A),begin(B),end(A),end(B)```), but usually this is indicates an error in the annotation placements rather than being intentional. It is inefficient, and in the worst case consumes lots of resources and leads to crashes. We therefore now stop region tracking and print an error message when we detect this situation. For intentionally overlapping regions, users should create attributes with the `CALI_ATTR_UNALIGNED` or `CALI_ATTR_NOMERGE` flags.
This change breaks Caliper region tracking in codes that have overlapping region annotations (usually inadvertently), even though it worked before. There's a config setting to restore the old behavior, but the best cause of action is to fix the annotations.
> Mark region end mismatches as errors by default

- include/caliper/Caliper.h
- include/caliper/common/Log.h
- src/caliper/CMakeLists.txt
- src/caliper/Caliper.cpp
- src/caliper/ConfigManager.cpp
- src/caliper/setup_mpi.cpp
- src/caliper/setup_serial.cpp
- src/common/Log.cpp
- src/mpi/CMakeLists.txt
- src/mpi/mpi_setup.cpp
- test/cali-annotation-perftest.cpp
Reworking the mpi library initialization so that cali_mpi_init() is no longer required.
> Rework mpi module initialization

- include/caliper/ChannelController.h
- These two variables will cause compilation errors in projects compiling against caliper with `-Wall -Werror`
> Fixed unused variable warnings in ChannelController.h

- src/caliper/controllers/HatchetRegionProfileController.cpp
- src/caliper/controllers/HatchetSampleProfileController.cpp
- src/caliper/controllers/controllers.cpp
- src/mpi/controllers/SpotController.cpp
- src/services/adiak/AdiakImport.cpp
- src/services/adiak/test/test_adiak.cpp
Adds the CALI_ADIAK_IMPORT_CATEGORIES config flag that lets users select adiak categories to import in the adiak_import service. It is accessible via the adiak.import_categories option in the ConfigManager.
> Filter adiak import categories

- src/services/adiak/AdiakImport.cpp
- src/services/adiak/test/test_adiak.cpp
Keep terminology between adiak and Caliper consistent: The old adiak.category attribute actually stored the adiak subcategory. Now it stores the (integer) category, and there is a new adiak.subcategory attribute for the subcategory.
> Fix adiak category attributes

- src/mpi/services/mpiwrap/Wrapper.w
- src/services/pthread/PthreadService.cpp
A workaround that fixes #288, but should really be addressed in gotcha (LLNL/GOTCHA#95).
> Use static buffers for gotcha wrapper lists

- src/services/cupti/Cupti.cpp
Cuda 11 doesn't properly zero out invalid kernel symbol entries in the CUpti callback structure, so our handler segfaults. Disable recording of the symbol name for now. Also some other cleanup.
> cupti: Don't record kernel symbol by default

- src/services/CMakeLists.txt
- src/services/gen_services_inc.py.in
- src/services/spot/Spot.cpp
- So, my IDE reports these warnings as errors when `gen_services_inc.py` runs so I just tweaked it to suppress them 
- in python, simply doing `if <string>` is the same as `if <string> != ""`
- Also, fixed a warning in Spot that popped up with a `for(const auto itr : <range>)` when it should be `for(const auto& itr : <range>)`
- Also, noticed this for the `-Wall` flag: `$<$<OR:$<CXX_COMPILER_ID:Clang>,$<CXX_COMPILER_ID:AppleClang>,$<CXX_COMPILER_ID:GNU>>:-Wall>` and since it was used privately and thus doesn't need a generator expression, I just dropped in a `check_cxx_compiler_flag` (which I have found to be _super_ useful in dealing with all these different compilers)
> Fixed "is not" with literal python warnings

- CMakeLists.txt
So this is just a proposal.
I was using the cmake GUI the other day and I noticed that all the caliper options `WITH_MPI`, etc. can be a little confusing (and potentially misleading) when caliper is a submodule and the project itself has an option like `USE_MPI` or `<project-name>_USE_MPI` option.
So this is a minor tweak such that caliper options can be prefixed with `"CALIPER_"`, i.e. `CALIPER_WITH_MPI` if `CALIPER_OPTION_PREFIX=ON` and it just does `set(WITH_<X> ${CALIPER_WITH_<X>})` locally.
> Added option for all caliper-specific options to be prefixied with "CALIPER_"

- cmake/WrapConfig.cmake
Caliper cannot be build if you have CMake 3.12 (or later) and only python 3. If you use CMake 3.12, `PYTHON_EXECUTABLE` is not set (https://github.com/LLNL/Caliper/blob/master/CMakeLists.txt#L353-L355). This means that we go in the else branch [here](https://github.com/LLNL/Caliper/blob/master/cmake/WrapConfig.cmake#L32-L38):
```
if (PYTHON_EXECUTABLE)
set(command ${PYTHON_EXECUTABLE})
set(script_arg ${Wrap_EXECUTABLE})
else()
set(command ${Wrap_EXECUTABLE})
set(script_arg "")
endif()
```
and we call the script directly. But the [script](https://github.com/LLNL/Caliper/blob/27af6ac221f9419e8fb0f95a35e6f706ad4d0cbd/src/mpi/services/mpiwrap/wrap.py) has 
```
#!/usr/bin/env python
```
and doesn't work python 3. It should be 
```
#!/usr/bin/env python3
```
Since python is always required, we …
> Fix cmake 3.19 and python 3.8 build

- src/mpi/controllers/LoopReportController.cpp
- src/mpi/controllers/SpotController.cpp
- test/ci_app_tests/ci_test_macros.cpp
- test/ci_app_tests/test_basictrace.py
- test/ci_app_tests/test_json.py
- test/ci_app_tests/test_loopreport.py
- test/ci_app_tests/test_monitor.py
- test/ci_app_tests/test_report.py
- test/ci_app_tests/test_runtimereport.py
- test/ci_app_tests/test_textlog.py
Correctly quote loop names in loop-report and spot controllers, so it does not break for loop names with spaces. Fixes #345. Thanks @Rombur for reporting this.
> Quote loop names in loop-report and spot. Fixes #345

- src/services/kokkos/KokkosProfilingSymbols.cpp
So, Kokkos has added the ability to pass command-line arguments to tools. This just adds support for that functionality, taking a single argument and converting it into an argument to be passed to a ConfigManager
> Support command line options

- CMakeLists.txt
So, I've had a few users now ask "why isn't the Kokkos Tool working" and for about half it's "didn't build with -DWITH_KOKKOS=ON." Given that these don't bring in any headers, would it be okay with you to just default to building these services?
> Default to build Kokkos services

- CMakeLists.txt
So basically this helps avoid "conflicting" installations when caliper is an internal dependency (i.e. caliper submodule and linked to caliper statically or with shared-libs and rpath and no `#include <caliper.h>` in the projects public headers). 
New CMake options are:
- `INSTALL_CONFIG` / `CALIPER_INSTALL_CONFIG`
- Defaults to TRUE
- When set to OFF, the CMake config and pkg-config files are not installed
- `INSTALL_HEADERS` / `CALIPER_INSTALL_HEADERS`
- Defaults to TRUE
- When set to OFF, none of the headers are installed
Example use case: non-development install of timemory python bindings with caliper built as a submodule.
> Options for suppressing install of caliper headers and/or cmake/pkg-config files

- include/caliper/CollectiveOutputChannel.h
- include/caliper/ConfigManager.h
- include/caliper/MpiChannelManager.h
- src/caliper/ConfigManager.cpp
- src/mpi/CMakeLists.txt
- src/mpi/CollectiveOutputChannel.cpp
- src/mpi/MpiChannelManager.cpp
- src/mpi/controllers/LoopReportController.cpp
- src/mpi/controllers/SpotController.cpp
- src/mpi/services/mpiwrap/Wrapper.w
- test/ci_app_tests/CMakeLists.txt
- test/ci_app_tests/ci_test_collective_output_channel.cpp
- test/ci_app_tests/ci_test_mpi_channel_manager.cpp
- test/ci_app_tests/test_mpi.py
Adds some infrastructure including the `MpiChannelManager` class to support ConfigManager channels running on sub-communicators.
> Support channels running on sub-communicators

- include/caliper/reader/QuerySpec.h
- src/caliper/controllers/CMakeLists.txt
- src/caliper/controllers/CallpathSampleReportController.cpp
- src/caliper/controllers/CudaActivityReportController.cpp
- src/caliper/controllers/RuntimeReportController.cpp
- src/caliper/controllers/controllers.cpp
- src/caliper/controllers/util.cpp
- src/caliper/controllers/util.h
- src/reader/CMakeLists.txt
- src/reader/CalQLParser.cpp
- src/reader/FormatProcessor.cpp
- src/reader/JsonFormatter.cpp
- src/reader/SnapshotTableFormatter.cpp
- src/reader/SnapshotTableFormatter.h
- src/reader/TableFormatter.cpp
- src/reader/TreeFormatter.cpp
- src/reader/UserFormatter.cpp
- src/reader/test/CMakeLists.txt
- src/reader/test/test_calqlparser.cpp
- src/reader/test/test_snapshottableformatter.cpp
- src/services/report/Report.cpp
- src/tools/cali-query/query_common.cpp
Adds print globals option for tree and table formatter and runtime-report, e.g. `runtime-report(print.metadata)`.  Also, formatter arguments in CalQL can now use kwargs instead of positional args. Addresses #380.
> Add print metadata option for reports

- cmake/WrapConfig.cmake
with the latest macOS and XCode,
this is needed or simple things
like stdio.h aren't found when
parsing mpi.h
> mpiwrap: include macOS SDK path

- src/mpi/services/mpiwrap/wrap.py
Functions like the following:
MPI_Type_create_f90_integer
do not have their symbols defined
in MPICH if MPICH is built without
Fortran support.
This change fixes undefined references
to those functions
when building against MPICH without
Fortran support.
> Don't wrap MPI functions containing 'f90'

- src/services/cupti/Cupti.cpp
- src/services/cupti/CuptiTrace.cpp
- src/services/sampler/Sampler.cpp
Move cupti and sampling cleanup to pre_finish_evt callback. Fixes potential race conditions on finalization.
> Move sampling/cupti finalization to pre_finish_evt

- src/caliper/controllers/ROCmActivityProfileController.cpp
- src/caliper/controllers/ROCmActivityReportController.cpp
The roctracer timestamps turn out to be slower, so we use Caliper's timestamps for the rocm configs.
> rocm: Use Caliper instead of rocm timestamps

- include/caliper/common/CaliperMetadataAccessInterface.h
- include/caliper/common/cali_types.h
- python/caliper-reader/caliperreader/metadatadb.py
- src/caliper/Caliper.cpp
- src/common/CaliperMetadataAccessInterface.cpp
- src/common/cali_types.c
- src/mpi/services/mpiwrap/MpiTracing.cpp
- src/services/aggregate/Aggregate.cpp
- src/services/alloc/AllocService.cpp
- src/services/cupti/CuptiTrace.cpp
- src/services/event/EventTrigger.cpp
- src/services/io/IOService.cpp
- src/services/libpfm/Libpfm.cpp
- src/services/memusage/MemUsageService.cpp
- src/services/monitor/LoopMonitor.cpp
- src/services/monitor/RegionMonitor.cpp
- src/services/papi/Papi.cpp
- src/services/pcp/Pcp.cpp
- src/services/pcp/PcpMemory.cpp
- src/services/roctracer/RocTracer.cpp
- src/services/templates/MeasurementService.cpp
- src/services/timestamp/Timestamp.cpp
- src/services/umpire/UmpireStatistics.cpp
- src/services/variorum/Variorum.cpp
This simplifies making metric attributes, which is a common use case.
> Use flag instead of metadata to mark metric attributes

- src/caliper/RegionFilter.cpp
this file uses std::istringstream, so needs
<sstream>. GCC doesn't complain but Clang does.
In particular, I get this on my Mac:
```
/Users/daibane/src/capp-alegra-ng/source/caliper/src/caliper/RegionFilter.cpp:146:28: error: implicit instantiation of undefined template 'std::basic_istringstream<char>'
std::istringstream is(include);
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/iosfwd:138:32: note: template is declared here
class _LIBCPP_TEMPLATE_VIS basic_istringstream;
^
/Users/daibane/src/capp-alegra-ng/source/caliper/src/caliper/RegionFilter.cpp:156:28: error: implicit instantiation of undefined template 'std::basic_istringstream<char>'
std::istringstream is(exclude);
^ …
```
> missing standard header

- python/cali2traceevent.py
- python/json2json_split.py
- src/caliper/controllers/controllers.cpp
Converts Caliper traces to Google TraceEvent format. Traces can be viewed in Chrome with chrome://tracing.
> Add a TraceEvent converter script

- include/caliper/common/util/callback.hpp
Remove std::forward<> in callback handlers. Not necessary and it leads to issues where arguments are being destroyed prematurely when there are multiple callbacks in the vector. In particular, the snapshot post-processing lambda was destroyed when there are multiple flush callback entries (e.g. using trace and aggregate combined) and caused crashes.
> Fix callbacks

- src/CMakeLists.txt
- src/caliper/CMakeLists.txt
- src/common/CMakeLists.txt
- src/common/test/CMakeLists.txt
- src/interface/c_fortran/CMakeLists.txt
- src/mpi/CMakeLists.txt
- src/mpi/services/mpiwrap/CMakeLists.txt
- src/reader/CMakeLists.txt
- src/reader/test/CMakeLists.txt
- src/services/CMakeLists.txt
- src/tools/cali-query/CMakeLists.txt
- src/tools/util/CMakeLists.txt
Use CMake's target_compile_features() to set required language standards instead of CMAKE_[C|CXX]_STANDARD.
> Use target_compile_features() to specify C++11 requirement

- include/caliper/reader/SnapshotTree.h
- src/caliper/ConfigManager.cpp
- src/caliper/controllers/RuntimeReportController.cpp
- src/caliper/controllers/controllers.cpp
- src/caliper/test/test_configmanager.cpp
- src/reader/SnapshotTree.cpp
- src/reader/TreeFormatter.cpp
- src/services/aggregate/Aggregate.cpp
- src/services/aggregate/AggregationDB.cpp
- src/services/aggregate/AggregationDB.h
New aggregate.slot attribute in aggregator retains the order in which entries were created. New node.order, order_as_visited, and order_by_time (for runtime-report) ConfigManager options. Also adds sorting capability to the tree formatter.
> Option to retain original visit order in output hierarchy

- src/caliper/MemoryPool.cpp
- src/caliper/MetadataTree.cpp
Makes it safe to hand out string pointers.
> Make sure we pad all variant allocations with 0-bytes

- examples/apps/CMakeLists.txt
- src/CMakeLists.txt
- src/common/CMakeLists.txt
- src/services/CMakeLists.txt
- test/ci_app_tests/CMakeLists.txt
Remove the public c_std_99 flag for the caliper and caliper-serial CMake targets. This is a workaround for an issue where CMake fails if a projects doesn't have the C language enabled. As a consequence target apps using the C interface must explicitly enable at least C99 support.
> Remove public c_std_99 cmake flag

- src/mpi/mpi_machine.cpp
Caliper build fails on master using Manjaro with GCC 13.
```
...
[ 65%] Building CXX object src/reader/CMakeFiles/caliper-reader.dir/RecordSelector.cpp.o
/home/dogiermann/Repos/Caliper-fork/src/mpi/mpi_machine.cpp:19:23: error: ‘uint64_t’ was not declared in this scope
19 | int get_rank_for_hash(uint64_t hash, MPI_Comm comm)
...
```
This PR adds the "missing" header to fix the build failure.
> Add missing std header for uint64_t

- src/caliper/controllers/SpotController.cpp
- src/caliper/controllers/controllers.cpp
- src/services/monitor/LoopMonitor.cpp
Adds min/max metrics for time.exclusive option in spot controller. Makes GPU and CPU metric names consistent. Removes default time interval setting for loop_monitor service (fixes #504).
> Some config spec updates

- python/caliper-reader/caliperreader/caliperstreamreader.py
- src/common/util/format_util.h
- src/reader/CaliReader.cpp
- src/reader/CaliWriter.cpp
- src/reader/JsonFormatter.cpp
- src/reader/JsonSplitFormatter.cpp
- test/ci_app_tests/ci_test_basic.cpp
- test/ci_app_tests/test_basictrace.py
Handle newlines in any strings provided to Caliper. Specifically fixes .cali and .json reading and writing by replacing newlines with `\n` and vice versa. Still best to not use newlines unless you know what you're doing, as they will still mess up the human-readable report formatters.
> Handle newlines in strings

- src/caliper/controllers/HatchetRegionProfileController.cpp
- src/caliper/controllers/HatchetSampleProfileController.cpp
- src/tools/cali-query/cali-query.cpp
- test/ci_app_tests/test_json.py
- test/ci_app_tests/test_ompt.py
- test/ci_app_tests/test_symbollookup.py
Makes .cali the default output format for hatchet-region-profile and hatchet-sample-profile. Adds time.inclusive metric for hatchet-region-profile. Also improves cali-query help strings.
> Hatchet profile recipe improvements

- src/caliper/controllers/CudaActivityProfileController.cpp
- src/caliper/controllers/CudaActivityReportController.cpp
- src/caliper/controllers/ROCmActivityProfileController.cpp
- src/caliper/controllers/ROCmActivityReportController.cpp
Use .cali format for the profile controllers. Add node order in all controllers. Plus, some general improvements.
> Update cuda and rocm controllers

- src/CMakeLists.txt
> Revert to linking MPI_CXX_LIBRARIES again

- doc/sphinx/RegionFiltering.rst
- include/caliper/cali.h
- include/caliper/cali_macros.h
- include/caliper/common/Attribute.h
- include/caliper/common/cali_types.h
- src/caliper/api.cpp
- src/caliper/cali.cpp
- src/caliper/controllers/controllers.cpp
- src/caliper/test/test_attribute.cpp
- src/common/cali_types.c
- src/services/event/EventTrigger.cpp
- test/ci_app_tests/ci_test_basic.cpp
- test/ci_app_tests/ci_test_macros.cpp
- test/ci_app_tests/test_basictrace.py
- test/ci_app_tests/test_cpuinfo.py
- test/ci_app_tests/test_json.py
- test/ci_app_tests/test_memusageservice.py
- test/ci_app_tests/test_papi.py
- test/ci_app_tests/test_report.py
- test/ci_app_tests/test_templateservices.py
Implements levels for region annotation attributes and filtering by level. Adds new macros `CALI_MARK_PHASE_BEGIN` and `CALI_MARK_PHASE_END` for higher-level than regular regions. Also implements a branch filter.
> Implement annotation levels

- src/services/mpiwrap/MpiWrap.cpp
- src/services/mpiwrap/Wrapper.w
- test/ci_app_tests/test_mpi.py
Disable the `mpi.call.id` attribute - we're not really using it anywhere right now. Addresses #545.
> Remove mpi.call.id

- src/services/sampler/Sampler.cpp
Remove workaround for old libunwind bug on aarch64 which should be fixed in recent versions. Fixes #559
> Remove aarch64 libunwind workaround

- src/common/util/format_util.h
we're seeing a compile failure on fedora 40
I believe newer compilers have lowered the number of indirect included headers, which means it needs adding in client code more often
```
caliper/src/common/util/format_util.h:17:32: error: 'uint64_t' has not been declared
write_uint64(std::ostream& os, uint64_t value)
```
> add cstdint header

- .gitlab-ci.yml
- .gitlab/jobs/lassen.yml
- .gitlab/jobs/tioga.yml
- src/services/monitor/Timeseries.cpp
> Update toolchains on tioga, lassen, ruby and poodle

- doc/sphinx/CaliperBasics.rst
- src/caliper/ChannelController.cpp
- src/caliper/ConfigManager.cpp
- test/ci_app_tests/test_basictrace.py
- test/ci_app_tests/test_spot.py
Adds `metadata` function for ConfigManager to pass in metadata through the config string. Also supports reading data from a json dictionary file.
> Add metadata via config strings

- include/caliper/cali_macros.h
- test/ci_app_tests/ci_test_macros.cpp
- test/ci_app_tests/test_basictrace.py
- test/ci_app_tests/test_json.py
- test/ci_app_tests/test_report.py
This PR fixes a bug with two Caliper macros:
- `CALI_CXX_MARK_FUNCTION`
- `CALI_CXX_MARK_SCOPE`
Both of these macros creates variables using special macros (i.e., `__func__` and `__LINE__`) and token concatenation (i.e., `##`). However, token concatenation prevents recursive evaluation of macros, which can cause compilation issues.
As an example, consider the following code:
```cpp
CALI_CXX_MARK_SCOPE("outer_region");
CALI_CXX_MARK_SCOPE("inner_region");
```
After pre-processing, the code would look like:
```cpp
cali::ScopeAnnotation __cali_ann_scope__LINE__("outer_region");
cali::ScopeAnnotation __cali_ann_scope__LINE__("inner_region");
```
Since these two variables have the same name, this code will fail to compile.
This PR fixes this bug by making use of the macro logic from [this …
> Fixes bug with variable naming in a couple of macros

- include/caliper/common/Variant.h
- src/common/Variant.cpp
- src/common/test/test_variant.cpp
- src/common/util/parse_util.h
- src/reader/RecordSelector.cpp
Improves `Variant::from_string()`. This should fix the xlc test failures on Lassen, even though they were probably due to a compiler bug. Also improves performance.
> Improve Variant::from_string()

- include/caliper/common/Variant.h
- src/common/Variant.cpp
- src/reader/Aggregator.cpp
- src/services/aggregate/Aggregate.cpp
- src/services/aggregate/AggregationDB.cpp
Retains the original data types in the aggregation service instead of converting everything to double.
> Retain data types in aggregation service

- src/common/util/parse_util.h
newer compilers can have less implicit includes
```
caliper/src/common/util/parse_util.h:40:24: error: 'uint64_t' was not declared in this scope
inline std::pair<bool, uint64_t>
^~~~~~~~
```
> include cstdint

- src/common/OutputStream.cpp
In gcc 8 `std::filesystem` support requires linking an extra `libstdc++-fs` library. No point in bothering with this so let's just not use std::filesystem in that version.
> Don't use std::filesystem with libstdc++ 8

- src/caliper/ConfigManager.cpp
- src/caliper/controllers/CudaActivityProfileController.cpp
- src/caliper/controllers/CudaActivityReportController.cpp
- src/caliper/controllers/HatchetRegionProfileController.cpp
- src/caliper/controllers/HatchetSampleProfileController.cpp
- src/caliper/controllers/LoopReportController.cpp
- src/caliper/controllers/ROCmActivityProfileController.cpp
- src/caliper/controllers/ROCmActivityReportController.cpp
- src/caliper/controllers/RuntimeReportController.cpp
- src/caliper/controllers/SampleReportController.cpp
- src/caliper/controllers/SpotController.cpp
- src/caliper/controllers/controllers.cpp
- src/services/adiak/AdiakImport.cpp
- src/services/aggregate/Aggregate.cpp
- src/services/alloc/AllocService.cpp
- src/services/callpath/Callpath.cpp
- src/services/event/EventTrigger.cpp
- src/services/monitor/LoopMonitor.cpp
- src/services/mpireport/MpiReport.cpp
- src/services/papi/Papi.cpp
- src/services/recorder/Recorder.cpp
- src/services/report/Report.cpp
- src/services/sampler/Sampler.cpp
- src/services/symbollookup/SymbolLookup.cpp
- src/services/textlog/TextLog.cpp
- src/services/timer/Timer.cpp
- src/services/trace/Trace.cpp
- src/services/umpire/UmpireStatistics.cpp
Splits up the long ConfigManager option spec string. Should fit with MSVC's 16KiB string literal size limit now. Also generally shortens the service and config recipe strings by removing whitespace.
> Split and shorten config recipe strings

- src/services/mpiwrap/wrap.py
> Skip empty MPI fn arg in wrap.py. Fixes #631.

- test/ci_app_tests/test_json.py
- test/ci_app_tests/test_loopreport.py
- test/ci_app_tests/test_monitor.py
- test/ci_app_tests/test_report.py
- test/ci_app_tests/test_textlog.py
Strings in some of our test code didn't escape backslashes properly, which causes a syntax error in Python 3.12.
> Properly escape backslashes in Python strings

- CMakeLists.txt
- cmake/FindRocTX.cmake
- cmake/FindRoctracer.cmake
Use the default `ROCM_PATH` variable instead of `ROCM_ROOT_DIR`. Fixes #637
> Use ROCM_PATH to look for roctracer/roctx. Fixes #637
